sonar.projectKey=Camilo-Marsel_front-fabrica-2026-1
sonar.organization=camilo-cespedes
sonar.projectName=Fábrica Escuela — Frontend

sonar.sources=app,components,hooks,lib
sonar.exclusions=**/.next/**,**/node_modules/**,**/public/**

sonar.javascript.lcov.reportPaths=coverage/lcov.info
sonar.coverage.exclusions=**/*.config.*,**/layout.tsx,**/middleware.ts
